[package]
name = "sc-consensus"
version = "0.8.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sc-client-api = { version = "2.0.0-dev", path = "../../api" }
sp-blockchain = { version = "2.0.0-dev", path = "../../../primitives/blockchain" }
sp-runtime = { version = "2.0.0-dev", path = "../../../primitives/runtime" }
sp-consensus = { version = "0.8.0-dev", path = "../../../primitives/consensus/common" }
